# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

boids_simulate_cpp <- function(x, y, z, vx, vy, vz, ids, species, bounds, boundary, obstacles, attractors, predators, params, steps, dt, record_every, dimension, use_grid, seed) {
    .Call(`_boids4R_boids_simulate_cpp`, x, y, z, vx, vy, vz, ids, species, bounds, boundary, obstacles, attractors, predators, params, steps, dt, record_every, dimension, use_grid, seed)
}

